# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install app dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install security tools
      run: |
        pip install bandit pip-audit

    - name: Run tests with pytest
      run: |
        pytest

    - name: Run Bandit (Python code security scan)
      run: |
        bandit -r .

    - name: Run pip-audit (Dependancy vulnerability scan)
      run: |
        pip install pip-audit
        pip-audit

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: Scan Docker image for vulnerabilities
      run: |
        docker build -t my-python-app .
        trivy image --exit-code 0 --severity HIGH,CRITICAL my-python-app
