name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:

  dev:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: dev
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests with pytest
      run: pytest

  security:
    name: Security Scans (Bandit & pip-audit)
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install security tools
      run: |
        pip install -r requirements.txt
        pip install bandit pip-audit
    - name: Run Bandit (Python code security scan)
      run: bandit -r .
    - name: Run pip-audit (Dependency vulnerability scan)
      run: pip-audit || true

  docker-scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: security
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t aslaf/my-python-app:latest .

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: Run Trivy Scan
      run: trivy image --exit-code 0 --severity HIGH,CRITICAL aslaf/my-python-app:latest

  docker-push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    needs: docker-scan
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: aslaf/my-python-app:latest
        platforms: linux/amd64