name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.EC2_PROJECT_DIR }}
          git pull origin main
          docker stop my-flask-app || true
          docker rm my-flask-app || true
          docker build -t my-flask-app .
